// Canonical English content. Other locales (ms/zh/ar) derive their structural
// fields (icons, image paths, hrefs, flags, proper nouns) from this file and
// override only the translatable strings — so non-text data lives in one place.
const en = {
  meta: {
    title: 'r450k — Private on-prem security & automation suite',
    description:
      'On-prem AI cameras, sensors and door access control with one fleet control plane and single sign-on: ONVIF discovery, YOLO detection, NVR recording, timeline playback, WebRTC video walls, case files with verifiable evidence export, OSDP badge readers, MQTT telemetry, and encryption at rest — running on hardware as small as a Raspberry Pi.',
  },
  brand: {
    name: 'r450k',
    tagline: 'Private on-prem security intelligence',
  },
  nav: [
    { label: 'Features', href: '#features' },
    { label: 'How it works', href: '#how' },
    { label: 'Hardware', href: '#tiers' },
    { label: 'Showcase', href: '#showcase' },
    { label: 'Use cases', href: '#use-cases' },
    { label: 'Apps', href: '#apps' },
    { label: 'Pricing', href: '#pricing' },
    { label: 'Download', href: '#download' },
  ],
  navCta: 'Explore apps',
  hero: {
    eyebrow: 'On-prem · Edge AI · No cloud required',
    titleLead: 'Security intelligence that runs',
    rotate: ['at the edge.', 'on your network.', 'on a Raspberry Pi.', 'without the cloud.'],
    subtitle:
      'r450k is a suite of apps that install on hardware you already own: AI cameras, building sensors and badge readers at the edge, one control plane that adopts them all and correlates events across them, and single sign-on tying it together. It scales from a single Raspberry Pi watching a couple of cameras to a GPU server running real-time AI across dozens. Your footage — and everything else — never leaves your network.',
    primaryCta: { label: 'See the features', href: '#features' },
    secondaryCta: { label: 'How it works', href: '#how' },
    stats: [
      { value: '5 apps', label: 'Cameras, sensors, doors, identity, fleet' },
      { value: '100%', label: 'On-prem, private by default' },
      { value: 'Raspberry Pi', label: 'Starts on a Pi 4 — scales to GPU servers' },
    ],
    note: 'Entry tier runs on a Raspberry Pi 4 (a couple of cameras with motion or nano-model AI). Real-time, multi-camera detection and teaching the camera your own skills scale up to mini-PCs and NVIDIA GPUs. The sensor hub, door controller, identity broker and control plane are single pure-Go binaries and need far less.',
  },
  features: {
    kicker: 'Capabilities',
    title: 'Everything a private, on-prem estate needs.',
    lead: 'Cameras, sensors, doors, identity and fleet management — built to run on small devices, entirely on your own network.',
    items: [
      {
        icon: 'eye',
        title: 'Camera-first AI detection',
        body: 'Two-axis rules pair a mode — presence, crowd, intrusion, line crossing, multi-line crossing, or LPR — with target classes from a data-driven registry, scoped to multiple detection zones per rule. Rules about a stretch of time rather than a single frame come as standard: loitering, left behind (and, by default, only when nobody is standing beside it), and direction of travel, all reading the same detections and tracking, so a camera already running detection pays nothing extra for them. Fire and smoke ship as first-class event classes, and an "Anything" wildcard fires on any detected object.',
      },
      {
        icon: 'car',
        title: 'License-plate recognition',
        body: 'A second-stage plate detector + OCR on a dedicated high-res frame fires on any readable plate or only a watchlist. Fuzzy matching absorbs OCR errors; plate text, vehicle type, and color ride the alert metadata.',
      },
      {
        icon: 'face',
        title: 'Face recognition',
        body: 'Enroll the people you know, and a detection becomes a named alert. On the edge node, faces are aligned, embedded, and matched against your private gallery — so “person detected” turns into “a known face at the front door.” Enrollment and matching run entirely on-prem: no cloud service, no faces ever leaving your network.',
      },
      {
        icon: 'privacy',
        title: 'Hide what must not be seen',
        body: 'Draw the neighbour’s window, the pavement outside the gate, or the keypad somebody types a PIN into, and the recorder asks the camera to black that area out itself — so those pixels are never recorded at all. It then reads the masks back off the camera and says, per camera and in plain words, whether that is confirmed rather than assumed. An export can black those areas out of the copy you hand over, and can be asked to paint over the faces in it too. The product is careful about which is which: a drawn zone is a guarantee, automatic face redaction is a best effort, and it says so beside the checkbox, on the finished file, and in the bundle’s manifest.',
      },
      {
        icon: 'record',
        title: 'NVR recording that checks itself',
        body: 'Rolling segment buffer with event-triggered MP4 clip extraction, plus a low-resource JPEG ring-buffer mode. Optional one-pass GPU H.265/H.264 re-encode shrinks footage with on-the-fly playback transcode for any browser. It also verifies that it actually recorded: a continuity monitor scores every closed hour against the footage really on disk and raises a gap alert when a camera stops writing, and a tamper monitor notices a lens covered, sprayed, knocked out of focus, or turned to face a wall.',
      },
      {
        icon: 'clock',
        title: 'Play it back by the clock',
        body: 'A timeline screen plays footage by wall-clock time instead of by file: scrub a bar shaded with the coverage you actually have, seek straight across segment boundaries, and hold up to eight cameras synchronised on one moment at 0.25×–8× speed, with detections plotted as clickable jump marks. Ask for a moment nothing covers and it tells you so, instead of quietly playing the next thing it found.',
      },
      {
        icon: 'play',
        title: 'Live view you can talk back through',
        body: 'Direct H.264 RTP-to-WebRTC live view with MJPEG fallback and live sound on any camera codec (G.711 pass-through, AAC→Opus transcoding). Two-way audio talk-back, press-and-hold PTZ, saved positions and guard tours let operators respond, not just watch. An arrangement worth keeping becomes a named video wall — stored on the appliance rather than in one browser, so it can be handed to the next shift — that cycles through its pages on its own and pulls a camera onto the visible page when it raises an alert. The control plane runs walls that span several recorders.',
      },
      {
        icon: 'bolt',
        title: 'Respond, not just record',
        body: 'Most cameras have a terminal block nobody uses. Wire a door contact, a beam, a PIR or a panic button into a camera input and it lands in the feed the moment it trips — named, filterable, filed as a sensor reading rather than an AI detection. Drive the relay output the other way to trigger a siren, a strobe, a gate or a light, by hand or when a rule fires, and a rule can swing a PTZ dome onto a saved position and hold it there while somebody looks. A rule can only ever pulse an output, never latch it, and the camera is asked to switch it back off wherever it will accept the job — so a restart cannot leave a siren sounding.',
      },
      {
        icon: 'sensor',
        title: 'Sensors, telemetry & safe actuation',
        body: 'The same idea as the NVR, but for everything that is not a camera: door contacts, motion, temperature, smoke, leaks, power meters and Modbus/SunSpec inverters, over an embedded MQTT broker — plus an opt-in, read-only LAN scan that finds what is already on the network. A deadbanded store keeps history small, threshold and correlation rules raise alerts, and scenes, schedules and a visual flow canvas automate the response. Every command back to a device is forced through one bounded, rate-limited, fully audited chokepoint.',
      },
      {
        icon: 'door',
        title: 'Access control at the door',
        body: 'Badge readers speak OSDP over RS-485 or IP, and every badge-in is decided on the appliance itself against people, groups, schedules and holidays — so a cut uplink never means a door that will not open. Site-wide lockdown, a duress PIN that opens the door while silently raising the alarm, and an append-only activity log come as standard, and the strike only ever fires through one audited chokepoint.',
      },
      {
        icon: 'network',
        title: 'Correlate cameras, sensors and doors',
        body: 'The rule no single appliance can write on its own: motion on a camera AND a door opening AND no badge accepted, inside the same window, at the same site. The control plane arms on the first signal, waits out a grace period for the innocent explanation, and only then raises one correlated incident instead of three unrelated alerts.',
      },
      {
        icon: 'lock',
        title: 'Encryption, backup & recovery',
        body: 'Recordings, snapshots, and training images are AES-256-GCM encrypted on disk; factory reset crypto-erases by destroying the key and multi-pass shreds deleted footage. The key is wrapped by an OS keystore (DPAPI / systemd-creds) or a portable passphrase with an exportable recovery escrow — and a passphrase-encrypted .mmbackup moves cameras, rules, and settings between hosts.',
      },
      {
        icon: 'brain',
        title: 'Teach it new skills',
        body: 'No ML jargon, no dataset wrangling. A guided wizard teaches the camera a new skill — name it, pick a goal (recognize a new object, tell good from bad, or spot anything unusual), show a few examples, check the accuracy, and turn it on. It builds and trains a real custom model behind the scenes, then hot-swaps the live detector.',
      },
      {
        icon: 'bell',
        title: 'Unified notification feed',
        body: 'One feed across AI detection, camera and machine health, and login security — with per-event acknowledge, annotated screenshots, and in-page clip playback. Filter the feed down to a single source camera to isolate one view’s events, or put any row straight into a case file from the screen where you noticed it. Route to email, webhook, Telegram or MQTT — or to a phone: add the fleet page to a home screen and it installs like an app, and registering a device sends a real notification there and then and reports what actually happened, rather than claiming a switch is on.',
      },
      {
        icon: 'link',
        title: 'Fleet pairing over the LAN',
        body: 'Authenticated UDP multicast discovery + single-parent adoption with a short-lived claim code. Nodes enroll for a fleet-CA certificate and serve a mutual-TLS management channel — no inbound ports, no cloud broker. Each node’s certificate auto-renews on an operator-gated schedule, so fleet trust stays current and no forgotten node lapses.',
      },
      {
        icon: 'map',
        title: 'Fleet maps & floor plans',
        body: 'The control plane puts your whole estate on a map — sites and buildings pinned by location, with every edge node and its cameras layered on top. Drop into a building to design its floor plan in-app, place each camera on the plan with a field-of-view coverage cone, and see one building’s cameras aggregated across several nodes. Click any camera to locate it or open its live view straight from the map.',
      },
      {
        icon: 'server',
        title: 'Run the fleet, not the appliances',
        body: 'Declare what a node’s settings ought to be — recording continuity, camera reachability, tamper detection, health thresholds, retention — and the control plane reports every quarter of an hour which appliances have drifted. It only reports, until you opt a policy into writing the value back. Upgrade in rings with a canary first, where a ring passes only when every node returned, reported the target version itself, and held it for a settle window. And answer what the fleet’s uptime WAS, not only what it is, per node, per site and per month — with the spans where the control plane itself was not watching counted rather than quietly skipped.',
      },
      {
        icon: 'failover',
        title: 'Survives losing an appliance',
        body: 'A recorder is the only thing recording its own cameras. Name a spare and it is kept supplied with that recorder’s camera list — then press Test on a quiet afternoon and the spare actually opens every one of those cameras and reports, per camera, whether it could and whether it has the headroom to keep them. Until you do, the plan says NEVER TESTED and nothing pretends otherwise. Flag the rules whose evidence must outlive the box and the fleet pulls those clips off the appliance and keeps its own hash-verified copy, for the case where the recording is destroyed by whoever set off the alarm. The control plane and the identity server themselves run as several instances behind a load balancer.',
      },
      {
        icon: 'sparkle',
        title: 'An analyst that reads the fleet for you',
        body: 'A daily — and optionally weekly — digest reads the whole estate and reports what changed: event-volume swings, a node breaking its own learned baseline, outages, expiring certificates, noisy sources, sensitive audit activity, even a suggested rule for after-hours activity nothing covers yet. Every number is computed in plain Go, so a digest finding is never a hallucination. An optional language model — your own endpoint, or a supervised sidecar you can carry in on a USB stick — adds an "ask the fleet" chat that cites the records it used and answers "how do I…" straight from the built-in manuals. It runs on your hardware or not at all.',
      },
      {
        icon: 'chart',
        title: 'Analytics dashboard',
        body: 'The unified event feed becomes insight — KPI tiles, detections over time, and per-category, per-camera breakdowns with a range selector and auto-refresh. It goes past charts: an activity heatmap by hour and weekday, an expected-range band that flags when a camera breaks its own normal pattern, spike and "unusual silence" anomaly alerts, a per-camera reliability scorecard, and a notification noise ratio. Aggregation runs server-side, so it works on SQLite or a full database engine.',
      },
      {
        icon: 'search',
        title: 'Object Search',
        body: 'Search your footage by what the cameras actually saw. Every detection is coalesced onto a searchable timeline — filter by camera, date range, one or more object types at once, and confidence, then jump straight to the exact moment in the recording, with the object boxed on a preview thumbnail. Export the results to CSV or PDF. It taps the live detector\'s own output, so there is no second video pass. Pick a recorded person or vehicle and "Find similar" ranks every other sighting on the appliance by appearance — and the control plane asks the same question of every node at once, merging what each recorder saw and recognized into one list.',
      },
      {
        icon: 'folder',
        title: 'Case files and verifiable evidence',
        body: 'An investigation gets somewhere to live. A case collects the footage, the sightings and the operator’s notes for one incident — bookmarked straight off the timeline or the notification feed, annotated with why each piece matters, handed to a colleague, and closed with a stated outcome. The part that makes it worth opening: while a case is open, retention, a manual purge and the clean-up that runs when the disk fills all refuse to delete the footage it points at. It exports as one bundle — the clips joined without re-encoding, a manifest naming each source segment and its SHA-256, the chain of custody as a CSV, and a plain-text note explaining how to check all of it with standard tools.',
      },
      {
        icon: 'shield',
        title: 'Enterprise identity, MFA & audit',
        body: 'One sign-on across every app, from a single pure-Go binary that never leaves your intranet. Local accounts alongside LDAP / Active Directory, Kerberos SPNEGO desktop SSO and generic OIDC providers, with group-to-role mapping and per-app, per-page access control. TOTP and WebAuthn security keys, password policy, lockout and step-up re-authentication guard the front door; an immutable audit trail, live session administration and passphrase-encrypted backup/restore keep it accountable.',
      },
      {
        icon: 'activity',
        title: 'Deploys and runs itself',
        body: 'A first-run wizard walks setup end to end in every app, a capacity estimator sizes your host, and machine-health monitoring self-heals — overwriting the oldest footage before the disk fills. Each app also carries its own printable four-language user manual compiled into the binary, readable offline from the sign-in screen. ffmpeg, the Python AI runtime, and app updates all install from inside the app.',
      },
    ],
  },
  how: {
    kicker: 'How it works',
    title: 'From bare devices to actionable alerts in four steps.',
    steps: [
      { n: '01', title: 'Discover', body: 'Authenticated ONVIF discovery and manual probe find cameras on your LAN, an enrollment window or read-only network scan finds sensors, and OSDP readers announce themselves on the bus. Saved devices persist in a local SQLite database.' },
      { n: '02', title: 'Detect', body: 'On-device YOLO inference runs your detection rules — presence, crowd, intrusion, line crossing, or plate recognition — against the live frames, while sensor thresholds and badge decisions are evaluated on the appliance itself.' },
      { n: '03', title: 'Record', body: 'Continuous NVR recording rolls in the background and extracts an MP4 clip the moment a rule fires, encrypted on disk; telemetry and every access decision land in their own append-only history. Play it back by the clock on the timeline, and pin what matters into a case file so retention cannot take it.' },
      { n: '04', title: 'Notify', body: 'Alerts land in the unified feed with an annotated snapshot and clip, correlate across cameras, sensors and doors at the control plane, and fan out to the email, webhook, Telegram, MQTT or phone destinations you choose.' },
    ],
  },
  tiers: {
    kicker: 'Hardware',
    title: 'Scales with your hardware.',
    lead: 'The camera node is the hungry one: it runs from a pocket-sized appliance to a GPU server, and you choose the tier. The sensor hub, door controller, identity broker and control plane are single pure-Go binaries that fit comfortably alongside it. (Camera counts are rough; the built-in capacity estimator measures the real number for your host.)',
    recommended: 'Recommended',
    items: [
      { name: 'Minimal', spec: 'Raspberry Pi 4/5 · 4 cores · 2–4 GB', load: '~1–4 cameras', detail: 'Live view + recording for a couple of cameras; AI is native motion or YOLO-nano at a relaxed interval. SQLite, CPU software decode, no GPU.' },
      { name: 'Optimal', spec: 'Mini-PC / NUC · 6–8 cores · 8–16 GB', load: '~6–16 cameras', detail: 'Continuous recording with real-time YOLO detection at the 2 s default. An entry NVIDIA GPU lifts camera count and keeps AI real-time.', featured: true },
      { name: 'Maximum', spec: 'Server · 12+ cores · 32 GB+ · NVIDIA GPU', load: '20+ cameras', detail: 'GPU-accelerated detection, in-app model training, HEVC NVENC compression, and long retention. Server DB engine + Redis at scale.' },
    ],
  },
  showcase: {
    kicker: 'See it in action',
    title: 'A console built for operators, not just admins.',
    lead: 'These screens are MyMataSan, the camera node: live multi-camera grids, detection rules drawn on the real frame, guided camera teaching with no ML jargon, continuous NVR recordings, event analytics, encrypted backups, and version & health. Every app in the suite shares the same shell — in the browser, in four languages.',
    tabs: { live: 'Live view', detection: 'AI detection', teach: 'Teach', recordings: 'Recordings', objectsearch: 'Object search', dashboard: 'Dashboard', heatmap: 'Activity heatmap', backup: 'Backup & recovery', health: 'Version & health' },
    shots: [
      { key: 'live', src: '/screenshots/live_views.png', alt: 'Live multi-camera grid in a 3×2 layout, with on-frame “Presence detected (person)” AI badges on two of the feeds', url: 'mymatasan.local/live' },
      { key: 'detection', src: '/screenshots/ai_detection.png', alt: 'AI Detection tab: a presence rule with a six-point detection zone drawn over the real camera frame in the zone editor', url: 'mymatasan.local/detection' },
      { key: 'teach', src: '/screenshots/teach.png', alt: 'Teach — the guided, no-jargon wizard for teaching the camera a new skill (Name it · What kind · Where · Show examples · Check accuracy · Turn it on), on the “What kind of skill is this?” step with three choices: recognize a new object, tell good from bad, or spot anything unusual', url: 'mymatasan.local/teach' },
      { key: 'recordings', src: '/screenshots/recordings.png', alt: 'Recordings page: a continuous-NVR day timeline with event-clip markers, and a list of clips with play, download, and delete', url: 'mymatasan.local/recordings' },
      { key: 'objectsearch', src: '/screenshots/object_search.png', alt: 'Object Search: a cross-camera, timeline search of what each camera saw — filtered by camera, date range, object type and confidence — where each result carries a footage thumbnail with the detected object boxed, plus play and maximize actions', url: 'mymatasan.local/object-search' },
      { key: 'dashboard', src: '/screenshots/dashboard.png', alt: 'Event-analytics dashboard: total, unread, critical and warning KPIs, an events-over-time bar chart, and category and severity donuts', url: 'mymatasan.local/dashboard' },
      { key: 'heatmap', src: '/screenshots/activity_heatmap.png', alt: 'Dashboard analytics: an activity heatmap of detections by hour of day and day of week, revealing when each camera is busiest', url: 'mymatasan.local/dashboard' },
      { key: 'backup', src: '/screenshots/backup_recovery.png', alt: 'Backup & Recovery settings: a passphrase-protected configuration backup of cameras, AI detection, notifications and app settings, with restore', url: 'mymatasan.local/settings/backup' },
      { key: 'health', src: '/screenshots/version_health_language_selection.png', alt: 'Version & Health settings shown in Arabic (right-to-left): app and core versions, an update check, and DB, cameras and cache service-health tiles', url: 'mymatasan.local/settings/version' },
    ],
  },
  useCases: {
    kicker: 'Use cases',
    title: 'Built for places that can’t send their data to the cloud.',
    items: [
      { title: 'Manufacturing & QA', body: 'Train a custom model to flag product defects, missing parts, or PPE gaps on the line — private, on-prem, with no per-seat AI fees.' },
      { title: 'Retail & forecourts', body: 'Crowd and intrusion alerts, plus license-plate recognition for forecourt and drive-through monitoring.' },
      { title: 'Warehouse & logistics', body: 'Watch loading docks and yards — vehicle and person detection with line-crossing at gates, all on edge hardware.' },
      { title: 'Property & perimeter', body: 'After-hours intrusion detection with secure, encrypted recording that stays on-site.' },
      { title: 'Access-controlled facilities', body: 'Badge readers, access schedules and site lockdown decided on-site, with the camera that watched the door and the sensor that felt it open reporting into the same timeline.' },
      { title: 'Agriculture & remote sites', body: 'Spot animals or intruders across land with poor or no connectivity; detection and recording run entirely locally.' },
      { title: 'Care homes & clinics', body: 'After-hours movement and fall-style alerts with footage that never leaves the building — privacy by default.' },
      { title: 'Industrial & utilities', body: 'Zone and line-crossing rules for restricted areas and equipment, on rugged hardware where uplinks are unreliable.' },
      { title: 'Multi-site fleets', body: 'A control plane adopts many edge nodes over the LAN — cameras, sensors and door controllers alike — maps every site and building, and relays live view back to operators, with per-building floor plans that place each camera and its coverage. It holds every site to one settings policy, upgrades the estate a ring at a time, reports what each site’s uptime actually was, and can fail a lost recorder over to a spare.' },
    ],
  },
  apps: {
    kicker: 'The platform',
    title: 'One platform, five apps.',
    subtitle: 'r450k is a modular platform. mymatasan is the edge camera node, myiotsan the edge sensor hub, and mypintusan the door controller; the control plane adopts all three and correlates events across them, and shared identity ties it together.',
    available: 'Available',
    platform: 'Platform',
    items: [
      { name: 'mymatasan', status: 'Flagship · in active development', available: true, body: 'The standalone edge camera & video-intelligence node: ONVIF, AI detection, NVR, WebRTC live view and saved video walls, timeline playback, case files with verifiable evidence export, encryption, and LAN pairing.' },
      { name: 'myiotsan', status: 'Sensor hub · available now', available: true, body: 'The NVR, but for sensors: door contacts, motion, temperature, smoke, leaks, power meters and Modbus/SunSpec inverters over an embedded MQTT broker — with rules, alerts, scenes and schedules, a visual flow canvas, safe actuation, and telemetry history.' },
      { name: 'mypintusan', status: 'Access control · in development', available: false, body: 'The door controller: OSDP badge readers over RS-485 or IP, with people, groups, schedules, holidays, site lockdown and a duress PIN all decided on the appliance itself, so a cut uplink never means a door that will not open. Adoptable into the fleet like any other node — not yet available to download.' },
      { name: 'myseliasan', status: 'Control plane · available now', available: true, body: 'The fleet control plane that discovers, adopts, and manages camera, sensor and door nodes alike — mapping every site, building, and node with per-building floor plans and camera coverage — and correlates events across them: motion on a camera AND a door opening AND no badge accepted. It holds the estate to a settings policy, upgrades it in rings, fails a recorder over to a spare that has been proved, runs a video wall spanning several recorders, writes the daily fleet digest, answers questions about the fleet, and renders printable PDF reports. It can run as several instances behind a load balancer.' },
      { name: 'myidsan', status: 'Identity · available now', available: true, body: 'The single sign-on front door: one federated identity across every app, with local accounts, enterprise LDAP / Active Directory, Kerberos SPNEGO desktop SSO, and generic OIDC providers — plus TOTP and WebAuthn multi-factor, group-to-role mapping, per-app access control, live session revocation that reaches the relying app, and an immutable audit trail recording which application each account was actually let into. A single pure-Go binary that runs fully on your intranet, no egress — one instance or several behind a load balancer.' },
    ],
  },
  downloads: {
    kicker: 'Get the apps',
    title: 'Download & self-host.',
    subtitle: 'Run one node at a single site, or a whole fleet from one control plane. Each is a single install with the web UI and a default config bundled. (mypintusan, the door controller, is still in development and not downloadable yet.)',
    license: 'Free for personal and non-commercial use — individuals, non-profits, education, and research. Commercial or in-business use, and any reselling, needs a commercial license.',
    latest: 'Latest release',
    windows: 'Windows',
    linux: 'Linux',
    docker: 'Docker',
    dockerHint: 'Run the multi-arch image:',
    // One block per product. Each releases on its own cadence, so each shows its own
    // version — the Worker resolves them from separate tags.
    products: {
      mymatasan: {
        name: 'MyMataSan',
        tagline: 'The edge node — one install per site. ONVIF cameras, on-device AI detection, NVR recording with continuity and tamper checks, WebRTC live view and video walls, timeline playback, and case files that export as verifiable evidence. Ships with the web UI, AI worker scripts and a default config.',
        dockerHint: 'Run the multi-arch image (ffmpeg included):',
      },
      myseliasan: {
        name: 'MySeliaSan',
        tagline: 'The fleet control plane — discover, adopt and manage many MyMataSan, MyIotSan and MyPintuSan nodes from one place, watch their cameras and sensors without ever exposing a node, and correlate events across all three. Holds the estate to a settings policy, upgrades it in rings, and fails a recorder over to a proved spare. A single pure-Go binary: no ffmpeg, no Python — run one instance, or several behind a load balancer.',
        dockerHint: 'Run the multi-arch image:',
      },
      myiotsan: {
        name: 'MyIotSan',
        tagline: 'The sensor hub — one install per site. Building & security sensors over an embedded MQTT broker, with a deadbanded telemetry store, threshold and correlation rules, alerts, and safe confirm-to-execute actuation. A single pure-Go binary: no ffmpeg, no Python. Opens an MQTT port (1883) for devices.',
        dockerHint: 'Run the multi-arch image (opens the MQTT port 1883 for devices):',
      },
      myidsan: {
        name: 'MyIDSan',
        tagline: 'The identity broker — one sign-on across every app. Local accounts plus enterprise LDAP / Active Directory, Kerberos SPNEGO desktop SSO and generic OIDC, with group-to-role mapping and per-app RBAC. A single pure-Go binary that runs entirely on your intranet: no ffmpeg, no Python, no egress.',
        dockerHint: 'Run the multi-arch image:',
      },
    },
    loading: 'Loading the latest release…',
    unavailable: 'Downloads are being prepared — check back shortly.',
    formTitle: 'Your download has started 🎉',
    formBlurb: 'Quick one before you go — how did you hear about us? It takes 10 seconds and helps a lot.',
    formClose: 'Close',
  },
  pricing: {
    kicker: 'Pricing',
    title: 'Free for you. Fair for business.',
    lead: 'Personal and non-commercial use is free — forever. Businesses keep the project alive with a simple commercial license. This is early pricing; we’ll tune it together as things grow.',
    popular: 'Most popular',
    tiers: [
      {
        name: 'Personal',
        price: 'Free',
        period: 'non-commercial',
        features: ['Every app, every feature, unlimited devices', 'On-device AI, NVR, encryption, backups', 'Personal, hobby, non-profit & education', 'Community support'],
        cta: 'Download',
        href: '#download',
      },
      {
        name: 'Business',
        price: '$149',
        period: '/ site · year',
        featured: true,
        features: ['Commercial license for one server / site', 'Unlimited cameras and devices on that server', 'All updates for the licensed term', 'Priority email support'],
        cta: 'Get a license',
        tallyForm: 'https://tally.so/r/rjWKeN',
      },
      {
        name: 'Fleet & Enterprise',
        price: 'Custom',
        period: 'multi-site',
        features: ['Many sites via the control plane', 'Custom AI model training & integration', 'Onboarding & priority support', 'Volume & OEM licensing'],
        cta: 'Contact us',
        tallyForm: 'https://tally.so/r/rjWKeN',
      },
    ],
    note: 'Prices in USD. Non-commercial use stays free. Not sure which fits? Reach out and we’ll figure it out together.',
    contactTitle: 'Contact us',
    contactBlurb: 'Tell us about your sites and what you need — we’ll get back to you.',
    contactClose: 'Close',
  },
  finalCta: {
    title: 'Keep your video — and your intelligence — on your own network.',
    body: 'r450k brings cloud-grade camera AI, sensor automation and access control to hardware you already own, with privacy as the default rather than an upgrade.',
    cta: { label: 'Explore the features', href: '#features' },
  },
  contact: {
    enabled: true,
    endpoint: '/api/contact',
    fabLabel: 'Contact',
    title: 'Get in touch',
    blurb: 'Send a message below and it lands straight in my Telegram.',
    namePlaceholder: 'Your name (optional)',
    messagePlaceholder: 'How can I help?',
    send: 'Send message',
    sending: 'Sending…',
    sent: 'Thanks — your message is on its way to my Telegram.',
    again: 'Send another',
    errRequired: 'Please enter a message.',
    errUnreachable: 'Message endpoint not reachable. (In local dev, run the Worker — see README.)',
    errGeneric: 'Something went wrong. Please try again.',
    support: 'Buy me a coffee',
    supportNudge: 'Even a small tip helps 💛',
    supportBlurb: 'If r450k saves you a cloud subscription, a coffee keeps it going.',
    supportUrl: 'https://buymeacoffee.com/mysayasan',
  },
  footer: {
    tagline: 'r450k · Private on-prem security intelligence',
    note: 'Runs on-prem. Your data never leaves your network.',
    rights: 'All rights reserved.',
    columns: [
      {
        heading: 'Product',
        links: [
          { label: 'Features', href: '#features' },
          { label: 'How it works', href: '#how' },
          { label: 'Use cases', href: '#use-cases' },
          { label: 'Pricing', href: '#pricing' },
          { label: 'Download', href: '#download' },
        ],
      },
    ],
  },
};

export default en;
