// Canonical English content. Other locales (ms/zh/ar) derive their structural
// fields (icons, image paths, hrefs, flags, proper nouns) from this file and
// override only the translatable strings — so non-text data lives in one place.
const en = {
  meta: {
    title: 'r450k — Private edge AI camera intelligence',
    description:
      'On-prem AI camera intelligence: ONVIF discovery, YOLO detection, NVR recording, WebRTC live view, and encryption at rest — running on hardware as small as a Raspberry Pi.',
  },
  brand: {
    name: 'r450k',
    tagline: 'Private edge AI camera intelligence',
  },
  nav: [
    { label: 'Features', href: '#features' },
    { label: 'How it works', href: '#how' },
    { label: 'Hardware', href: '#tiers' },
    { label: 'Showcase', href: '#showcase' },
    { label: 'Use cases', href: '#use-cases' },
    { label: 'Apps', href: '#apps' },
    { label: 'Pricing', href: '#pricing' },
    { label: 'Download', href: '#download' },
  ],
  navCta: 'Explore apps',
  hero: {
    eyebrow: 'On-prem · Edge AI · No cloud required',
    titleLead: 'AI camera intelligence that runs',
    rotate: ['at the edge.', 'on your network.', 'on a Raspberry Pi.', 'without the cloud.'],
    subtitle:
      'r450k discovers your ONVIF cameras, detects what matters with on-device AI, records continuously, and streams live to the browser. It scales with your hardware — from a single Raspberry Pi watching a couple of cameras to a GPU server running real-time AI across dozens. Your footage never leaves your network.',
    primaryCta: { label: 'See the features', href: '#features' },
    secondaryCta: { label: 'How it works', href: '#how' },
    stats: [
      { value: 'Raspberry Pi', label: 'Starts on a Pi 4 — scales to GPU servers' },
      { value: '100%', label: 'On-prem, private by default' },
      { value: 'WebRTC', label: 'Low-latency live view' },
    ],
    note: 'Entry tier runs on a Raspberry Pi 4 (a couple of cameras with motion or nano-model AI). Real-time, multi-camera detection and teaching the camera your own skills scale up to mini-PCs and NVIDIA GPUs.',
  },
  features: {
    kicker: 'Capabilities',
    title: 'Everything an edge AI camera node needs.',
    lead: 'Detection, recording, live view, security, and fleet management — built to run on small devices, entirely on your own network.',
    items: [
      {
        icon: 'eye',
        title: 'Camera-first AI detection',
        body: 'Two-axis rules pair a mode — presence, crowd, intrusion, line crossing, multi-line crossing, or LPR — with target classes from a data-driven registry, scoped to multiple detection zones per rule. Fire and smoke ship as first-class event classes, and an "Anything" wildcard fires on any detected object.',
      },
      {
        icon: 'car',
        title: 'License-plate recognition',
        body: 'A second-stage plate detector + OCR on a dedicated high-res frame fires on any readable plate or only a watchlist. Fuzzy matching absorbs OCR errors; plate text, vehicle type, and color ride the alert metadata.',
      },
      {
        icon: 'record',
        title: 'NVR recording + compression',
        body: 'Rolling segment buffer with event-triggered MP4 clip extraction, plus a low-resource JPEG ring-buffer mode. Optional one-pass GPU H.265/H.264 re-encode shrinks footage with on-the-fly playback transcode for any browser.',
      },
      {
        icon: 'play',
        title: 'Live view you can talk back through',
        body: 'Direct H.264 RTP-to-WebRTC live view with MJPEG fallback and live sound on any camera codec (G.711 pass-through, AAC→Opus transcoding). Two-way audio talk-back and press-and-hold PTZ let operators respond, not just watch — across paged grids from 1×1 to 4×4.',
      },
      {
        icon: 'lock',
        title: 'Encryption, backup & recovery',
        body: 'Recordings, snapshots, and training images are AES-256-GCM encrypted on disk; factory reset crypto-erases by destroying the key and multi-pass shreds deleted footage. The key is wrapped by an OS keystore (DPAPI / systemd-creds) or a portable passphrase with an exportable recovery escrow — and a passphrase-encrypted .mmbackup moves cameras, rules, and settings between hosts.',
      },
      {
        icon: 'brain',
        title: 'Teach it new skills',
        body: 'No ML jargon, no dataset wrangling. A guided wizard teaches the camera a new skill — name it, pick a goal (recognize a new object, tell good from bad, or spot anything unusual), show a few examples, check the accuracy, and turn it on. It builds and trains a real custom model behind the scenes, then hot-swaps the live detector.',
      },
      {
        icon: 'bell',
        title: 'Unified notification feed',
        body: 'One feed across AI detection, camera and machine health, and login security — with per-event acknowledge, annotated screenshots, and in-page clip playback. Route to webhook, Telegram, or MQTT.',
      },
      {
        icon: 'link',
        title: 'Fleet pairing over the LAN',
        body: 'Authenticated UDP multicast discovery + single-parent adoption with a short-lived claim code. Nodes enroll for a fleet-CA certificate and serve a mutual-TLS management channel — no inbound ports, no cloud broker.',
      },
      {
        icon: 'chart',
        title: 'Analytics dashboard',
        body: 'A live dashboard turns the unified event feed into insight — KPI tiles, detections over time, and per-category and per-camera breakdowns with a range selector and auto-refresh. Aggregation runs server-side, so it works on SQLite or a full database engine.',
      },
      {
        icon: 'activity',
        title: 'Deploys and runs itself',
        body: 'A first-run wizard walks setup end to end, a capacity estimator sizes your host, and machine-health monitoring self-heals — overwriting the oldest footage before the disk fills. ffmpeg, the Python AI runtime, and app updates all install from inside the app.',
      },
    ],
  },
  how: {
    kicker: 'How it works',
    title: 'From bare cameras to actionable alerts in four steps.',
    steps: [
      { n: '01', title: 'Discover', body: 'Authenticated ONVIF discovery and manual probe find cameras on your LAN; saved devices persist in a local SQLite database.' },
      { n: '02', title: 'Detect', body: 'On-device YOLO inference runs your detection rules — presence, crowd, intrusion, line crossing, or plate recognition — against the live frames.' },
      { n: '03', title: 'Record', body: 'Continuous NVR recording rolls in the background and extracts an MP4 clip the moment a rule fires, encrypted on disk.' },
      { n: '04', title: 'Notify', body: 'Alerts land in the unified feed with an annotated snapshot and clip, and fan out to webhook, Telegram, or MQTT destinations you choose.' },
    ],
  },
  tiers: {
    kicker: 'Hardware',
    title: 'Scales with your hardware.',
    lead: 'The same app runs from a pocket-sized appliance to a GPU server — you choose the tier. (Camera counts are rough; the built-in capacity estimator measures the real number for your host.)',
    recommended: 'Recommended',
    items: [
      { name: 'Minimal', spec: 'Raspberry Pi 4/5 · 4 cores · 2–4 GB', load: '~1–4 cameras', detail: 'Live view + recording for a couple of cameras; AI is native motion or YOLO-nano at a relaxed interval. SQLite, CPU software decode, no GPU.' },
      { name: 'Optimal', spec: 'Mini-PC / NUC · 6–8 cores · 8–16 GB', load: '~6–16 cameras', detail: 'Continuous recording with real-time YOLO detection at the 2 s default. An entry NVIDIA GPU lifts camera count and keeps AI real-time.', featured: true },
      { name: 'Maximum', spec: 'Server · 12+ cores · 32 GB+ · NVIDIA GPU', load: '20+ cameras', detail: 'GPU-accelerated detection, in-app model training, HEVC NVENC compression, and long retention. Server DB engine + Redis at scale.' },
    ],
  },
  showcase: {
    kicker: 'See it in action',
    title: 'A console built for operators, not just admins.',
    lead: 'Live multi-camera grids, detection rules drawn on the real frame, guided camera teaching with no ML jargon, continuous NVR recordings, event analytics, encrypted backups, and version & health — every screen in the browser, in four languages.',
    tabs: { live: 'Live view', detection: 'AI detection', teach: 'Teach', recordings: 'Recordings', dashboard: 'Dashboard', backup: 'Backup & recovery', health: 'Version & health' },
    shots: [
      { key: 'live', src: '/screenshots/live_views.png', alt: 'Live multi-camera grid in a 3×2 layout, with on-frame “Presence detected (person)” AI badges on two of the feeds', url: 'mymatasan.local/live' },
      { key: 'detection', src: '/screenshots/ai_detection.png', alt: 'AI Detection tab: a presence rule with a six-point detection zone drawn over the real camera frame in the zone editor', url: 'mymatasan.local/detection' },
      { key: 'teach', src: '/screenshots/teach.png', alt: 'Teach — the guided, no-jargon wizard for teaching the camera a new skill (Name it · What kind · Where · Show examples · Check accuracy · Turn it on), on the “What kind of skill is this?” step with three choices: recognize a new object, tell good from bad, or spot anything unusual', url: 'mymatasan.local/teach' },
      { key: 'recordings', src: '/screenshots/recordings.png', alt: 'Recordings page: a continuous-NVR day timeline with event-clip markers, and a list of clips with play, download, and delete', url: 'mymatasan.local/recordings' },
      { key: 'dashboard', src: '/screenshots/dashboard.png', alt: 'Event-analytics dashboard: total, unread, critical and warning KPIs, an events-over-time bar chart, and category and severity donuts', url: 'mymatasan.local/dashboard' },
      { key: 'backup', src: '/screenshots/backup_recovery.png', alt: 'Backup & Recovery settings: a passphrase-protected configuration backup of cameras, AI detection, notifications and app settings, with restore', url: 'mymatasan.local/settings/backup' },
      { key: 'health', src: '/screenshots/version_health_language_selection.png', alt: 'Version & Health settings shown in Arabic (right-to-left): app and core versions, an update check, and DB, cameras and cache service-health tiles', url: 'mymatasan.local/settings/version' },
    ],
  },
  useCases: {
    kicker: 'Use cases',
    title: 'Built for places that can’t send video to the cloud.',
    items: [
      { title: 'Manufacturing & QA', body: 'Train a custom model to flag product defects, missing parts, or PPE gaps on the line — private, on-prem, with no per-seat AI fees.' },
      { title: 'Retail & forecourts', body: 'Crowd and intrusion alerts, plus license-plate recognition for forecourt and drive-through monitoring.' },
      { title: 'Warehouse & logistics', body: 'Watch loading docks and yards — vehicle and person detection with line-crossing at gates, all on edge hardware.' },
      { title: 'Property & perimeter', body: 'After-hours intrusion detection with secure, encrypted recording that stays on-site.' },
      { title: 'Agriculture & remote sites', body: 'Spot animals or intruders across land with poor or no connectivity; detection and recording run entirely locally.' },
      { title: 'Care homes & clinics', body: 'After-hours movement and fall-style alerts with footage that never leaves the building — privacy by default.' },
      { title: 'Industrial & utilities', body: 'Zone and line-crossing rules for restricted areas and equipment, on rugged hardware where uplinks are unreliable.' },
      { title: 'Multi-site fleets', body: 'A control plane adopts many edge nodes over the LAN and relays live view back to operators.' },
    ],
  },
  apps: {
    kicker: 'The platform',
    title: 'One platform, three apps.',
    subtitle: 'r450k is a modular platform. mymatasan is the edge surveillance node; the control plane handles identity and fleet management.',
    available: 'Available',
    platform: 'Platform',
    items: [
      { name: 'mymatasan', status: 'Flagship · in active development', available: true, body: 'The standalone edge camera & video-intelligence node: ONVIF, AI detection, NVR, WebRTC live view, encryption, and LAN pairing.' },
      { name: 'myseliasan', status: 'Control plane', available: false, body: 'The fleet control plane that discovers, adopts, and manages edge nodes, and relays their live camera streams to operators.' },
      { name: 'myidsan', status: 'Identity', available: false, body: 'Shared identity and access: JWT auth, SSO, and role-based access control across the platform.' },
    ],
  },
  downloads: {
    kicker: 'Get MyMataSan',
    title: 'Download & self-host.',
    subtitle: 'The mymatasan edge node is a single install. Pick your platform — the web UI, AI worker scripts, and a default config come bundled.',
    license: 'Free for personal and non-commercial use — individuals, non-profits, education, and research. Commercial or in-business use, and any reselling, needs a commercial license.',
    latest: 'Latest release',
    windows: 'Windows',
    linux: 'Linux',
    docker: 'Docker',
    dockerHint: 'Run the multi-arch image (ffmpeg included):',
    loading: 'Loading the latest release…',
    unavailable: 'Downloads are being prepared — check back shortly.',
    formTitle: 'Your download has started 🎉',
    formBlurb: 'Quick one before you go — how did you hear about us? It takes 10 seconds and helps a lot.',
    formClose: 'Close',
  },
  pricing: {
    kicker: 'Pricing',
    title: 'Free for you. Fair for business.',
    lead: 'Personal and non-commercial use is free — forever. Businesses keep the project alive with a simple commercial license. This is early pricing; we’ll tune it together as things grow.',
    popular: 'Most popular',
    tiers: [
      {
        name: 'Personal',
        price: 'Free',
        period: 'non-commercial',
        features: ['Every feature, unlimited cameras', 'On-device AI, NVR, encryption, backups', 'Personal, hobby, non-profit & education', 'Community support'],
        cta: 'Download',
        href: '#download',
      },
      {
        name: 'Business',
        price: '$149',
        period: '/ site · year',
        featured: true,
        features: ['Commercial license for one server / site', 'Unlimited cameras on that server', 'All updates for the licensed term', 'Priority email support'],
        cta: 'Get a license',
        href: 'mailto:mysayasan@gmail.com?subject=MyMataSan%20commercial%20license',
      },
      {
        name: 'Fleet & Enterprise',
        price: 'Custom',
        period: 'multi-site',
        features: ['Many sites via the control plane', 'Custom AI model training & integration', 'Onboarding & priority support', 'Volume & OEM licensing'],
        cta: 'Contact us',
        tallyForm: 'https://tally.so/r/rjWKeN',
      },
    ],
    note: 'Prices in USD. Non-commercial use stays free. Not sure which fits? Reach out and we’ll figure it out together.',
    contactTitle: 'Contact us',
    contactBlurb: 'Tell us about your sites and what you need — we’ll get back to you.',
    contactClose: 'Close',
  },
  finalCta: {
    title: 'Keep your video — and your intelligence — on your own network.',
    body: 'r450k brings cloud-grade camera AI to hardware you already own, with privacy as the default rather than an upgrade.',
    cta: { label: 'Explore the features', href: '#features' },
  },
  contact: {
    enabled: true,
    endpoint: '/api/contact',
    fabLabel: 'Contact',
    title: 'Get in touch',
    blurb: 'Send a message below and it lands straight in my Telegram.',
    namePlaceholder: 'Your name (optional)',
    messagePlaceholder: 'How can I help?',
    send: 'Send message',
    sending: 'Sending…',
    sent: 'Thanks — your message is on its way to my Telegram.',
    again: 'Send another',
    errRequired: 'Please enter a message.',
    errUnreachable: 'Message endpoint not reachable. (In local dev, run the Worker — see README.)',
    errGeneric: 'Something went wrong. Please try again.',
    support: 'Buy me a coffee',
    supportNudge: 'Even a small tip helps 💛',
    supportBlurb: 'If r450k saves you a cloud subscription, a coffee keeps it going.',
    supportUrl: 'https://buymeacoffee.com/mysayasan',
  },
  footer: {
    tagline: 'r450k · Private edge AI camera intelligence',
    note: 'Runs on-prem. Your footage never leaves your network.',
    rights: 'All rights reserved.',
    columns: [
      {
        heading: 'Product',
        links: [
          { label: 'Features', href: '#features' },
          { label: 'How it works', href: '#how' },
          { label: 'Use cases', href: '#use-cases' },
          { label: 'Pricing', href: '#pricing' },
          { label: 'Download', href: '#download' },
        ],
      },
    ],
  },
};

export default en;
